name: Build & test

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    -
      name: Build
      working-directory: src
      run: dotnet build --configuration Release
    -
      name: Unit tests
      working-directory: src/tests/UnitTests
      run: dotnet test
    -
      name: Integration tests
      working-directory: src/tests/IntegrationTests
      run: dotnet test