# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

name: Build & test
on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v1
    -
      name: Build
      working-directory: src
      run: dotnet build --configuration Release
    -
      name: Unit tests
      working-directory: src/tests/UnitTests
      run: dotnet test
    -
      name: Integration tests
      working-directory: src/tests/IntegrationTests
      run: dotnet test